[project]
name = "ai-mcp-net-analysis"
version = "0.1.0"
description = "nmap based Model Context Protocol module"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "pyyaml>=6.0.2",
    "schema>=0.7.7",
]
