mcp:
  name: "ai-mcp-net-analysis"
  version: "1.0.0"
  description: "ai-mcp-net-analysis is a microservice for analyzing network data using LLMs."

logging:
  name: "ai-mcp-net-analysis-server"
  level: "DEBUG"
  type: "file"
  file:
    enabled: true
    path: "logs/ai-mcp-net-analysis-server.log"
    max_size_mb: 10
    backup_count: 5
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
